name: Update ICS Feed

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt
      - run: python generate_ics.py

      - name: Commit updated ICS
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add decatur.ics
          git commit -m "Update decatur.ics" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

