name: Token Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create test file
        run: echo "test: $(date)" >> test.txt

      - name: Commit and push test file
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add test.txt
          git commit -m "Test push" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
